services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    command:
      - '--path.procfs=/host/proc' # Specify the proc filesystem path for node exporter
      - '--path.sysfs=/host/sys' # Specify the sys filesystem path for node exporter
      - '--path.rootfs=/host' # Specify the root filesystem path for node exporter
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)' # Ignore certain mount points for filesystem metrics
    volumes:
      - /proc:/host/proc:ro # Mount the host's /proc filesystem as read-only to the container
      - /sys:/host/sys:ro # Mount the host's /sys filesystem as read-only to the container
      - /:/host:ro # Mount the host's root filesystem as read-only to the container
    expose:
      - "9100" # Expose port 9100 for node exporter metrics
    ports:
      - "9100:9100" # Map port 9100 of the host to port 9100 of the container
    networks:
      - monitoring # Connect the node exporter container to the 'monitoring' network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000" # Map port 3000 of the host to port 3000 of the container for Grafana web interface
    networks:
      - monitoring # Connect the Grafana container to the 'monitoring' network
      
    volumes:
      - grafana_data:/var/lib/grafana # Persist Grafana data in a Docker volume

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    command:
      - '--config.file=/etc/prometheus/prometheus.yml' # Load the Prometheus configuration file
      - '--storage.tsdb.path=/prometheus' # Specify the path for the time series database
      - '--web.console.libraries=/etc/prometheus/console_libraries' # Specify the path for console libraries
      - '--web.console.templates=/etc/prometheus/consoles' # Specify the path for console templates
      - '--web.enable-lifecycle' # Enable lifecycle management

    expose:
      - "9090" # Expose port 9090 for Prometheus web interface

    ports:
      - "9090:9090" # Map port 9090 of the host to port 9090 of the container

    networks:
      - monitoring # Connect the Prometheus container to the 'monitoring' network

  notes-app:
    build:
      context: ./notes-app # Build the notes app Docker image from the specified context directory
      dockerfile: Dockerfile
    container_name: notes-app
    restart: always
    ports:
      - "8000:8000" # Map port 8000 of the host to port 8000 of the container for the notes app
    networks:
      - monitoring # Connect the notes app container to the 'monitoring' network

  cadviser:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadviser
    restart: always
    ports:
      - "8080:8080" # Map port 8080 of the host to port 8080 of the container for cAdvisor web interface
    volumes:
      - /:/rootfs:ro # Mount the host's root filesystem as read-only to the container
      - /var/run:/var/run:rw # Mount the host's /var/run directory to the container with read-write permissions
      - /sys:/sys:ro # Mount the host's /sys filesystem as read-only to the container
      - /var/lib/docker/:/var/lib/docker:ro # Mount the host's Docker data directory as read-only to the container

    networks:
      - monitoring # Connect the cAdvisor container to the 'monitoring' network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100" # Map port 3100 of the host to port 3100 of the container for Loki API
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml # Mount the Loki configuration file from the host to the container
      - loki_data:/loki # Persist Loki data in a Docker volume
    command:
      - '-config.file=/etc/loki/local-config.yaml' # Load the Loki configuration file
    networks:
      - monitoring # Connect the Loki container to the 'monitoring' network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - ./promtail.yml:/etc/promtail/config.yaml:ro # Mount the Promtail configuration file from the host to the container
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Mount the host's Docker containers directory as read-only to the container
      - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket to the container for Promtail to access Docker logs
    command:
      - '-config.file=/etc/promtail/config.yaml' # Load the Promtail configuration file
    depends_on:
      - loki # Ensure that Promtail starts after Loki is up and running
    networks:
      - monitoring # Connect the Promtail container to the 'monitoring' network

networks:
  monitoring:
    driver: bridge # The bridge driver creates a private internal network on the host system, allowing containers to communicate with each other while isolating them from the host network.

volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}

